%{
  fulfillment_stats: %{
    "puppy_about_to_bump in about_to_bump": [],
    "puppy_approaches_food in getting_closer_to_food": [{ 0, 0, nil }],
    "puppy_approaching_obstacle in approaching_obstacle": [],
    "puppy_faces_food in getting_closer_to_food": [{ 0, 1, "By doing turn_toward" }],
    "puppy_has_clear_path in free": [{ 0, 0, nil }],
    "puppy_in_high_ambient_light in in_the_light": [{ 0, 0, nil }],
    "puppy_is_free in thriving": [],
    "puppy_is_moving in free": [
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil }
    ],
    "puppy_is_sated in thriving": [{ 0, 3, "By doing say_once" }],
    "puppy_not_about_to_bump in safe": [
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil }
    ],
    "puppy_not_bumping in safe": [
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil }
    ],
    "puppy_on_food in feeding": [{ 0, 7, "By believing getting_closer_to_food" }],
    "puppy_recently_ate in sated": [{ 0, 3, "By believing feeding" }],
    "puppy_recently_touched in bumped": [],
    "puppy_smells_food in getting_closer_to_food": [
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil }
    ],
    "puppy_unobstructed in free": [
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil },
      { 0, 0, nil }
    ]
  },
  prediction_error_stats: %{
    puppy_about_to_bump: 14,
    puppy_approaches_food: 1,
    puppy_approaching_obstacle: 2,
    puppy_faces_food: 2,
    puppy_is_free: 1,
    puppy_is_moving: 1,
    puppy_is_sated: 4,
    puppy_on_food: 8,
    puppy_recently_ate: 4,
    puppy_recently_touched: 14
  },
  prediction_fulfilled_stats: %{
    puppy_has_clear_path: 2,
    puppy_in_high_ambient_light: 3,
    puppy_not_about_to_bump: 14,
    puppy_not_bumping: 14,
    puppy_smells_food: 4,
    puppy_unobstructed: 2
  }
}
